### ISSUE TITLE
Heading structuur

### ISSUE THREAD

**Issue by KrijnHoetmer** [Harsves/the-client-case#1]
Is de h3 je eerste heading?

https://github.com/Harsves/the-client-case/blob/6559a1a607c4e5e48248422533c5d8b24c273903/kennisbank.html#L45

**Comment by Harsves** [comment]
Vooralsnog wel, maar de planning is om nog een titel erboven te zetten. Moet alleen even kijken als ik straks klaar ben met deze pagina of ik het gewoon kennisbank ga noemen of net als de WCAG pagina in verschillende koppen (Techniek, Redactie en Ontwerp).
